### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by dfroh40**
I made some more updates to address the parts of #13 that have not already been resolved.

### CODE REVIEW

**Comment by dfroh40** [comment]
I added the changes from #25 since a lot of work would be redundant.

**Review by SNSTRUTHERS — COMMENTED** [review]
Only the devdocs & userDocs need to be updated; faq & instructions are in a separate PR (#25).

**Comment by PhDN** [comment]
Can we unlink the add-faq PR or it doesn't matter?

**Comment by SNSTRUTHERS** [comment]
doesn't matter

**Review by ammarj0987 — APPROVED** [review]

**Pull request merged**
