### PR TITLE
Backend CI Fix

### LINKED ISSUE #7: Backend CI
We need to setup the CI testing with the backend.

### PR DESCRIPTION
**Pull request by dfroh40**
Added to actions.yml so that sets up the dependencies and runs the tests for the backend to resolve #7.

### CODE REVIEW

**Comment by dfroh40** [comment]
Ok, the backend tests are failing due to import errors. This indicates it has something to do with the way the files are setup. The command line improvements from #12 may be necessary to get test_model working, but the fact it is happening with test_controller as well means it is likely a general issue.

**Comment by dfroh40** [comment]
It looks like we need to set it up so that it runs the tests as a module and/or adds the working directory to the PATH. This needs to be done with Pytest, and not the standard Python command, which complicates things.

**Review by SNSTRUTHERS — COMMENTED** [review]
Works both on- and offline (Actions & command line, respectively); I'd say this is a yes :+1:

**Review by PhDN — COMMENTED** [review]
Approved

**Pull request merged**
